# Generated by Django 3.2.25 on 2024-07-28 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='error', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='error', max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField(choices=[('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)], default=5)),
                ('title', models.CharField(default=None, max_length=40)),
                ('content', models.CharField(default=None, max_length=1000)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
