# Generated by Django 3.2.25 on 2024-10-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240728_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release_date',
        ),
    ]
