# Generated by Django 3.2.25 on 2024-10-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_back',
            field=models.ImageField(default=None, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_front',
            field=models.ImageField(default=None, upload_to='covers'),
        ),
    ]
